### ISSUE TITLE
Question: why not using terraform

### ISSUE THREAD

**Issue by magodo** [mbrt/gmailctl#137]
Hi Michele, `gmailctrl` is really a great and handy tool, congratulations :+1:
Inspired by your idea, I want to have a counterpart for Outlook. Whilst instead of creating such a complex tool from scratch, I choose to use Terraform as it has done a lot of heavy lift. The remaining work is simply to write a Terraform extension.
I just wonder what considerations do you have not to choose Terraform, but write your own tool?

**Comment by mbrt** [comment]
I think using Terraform is a good idea. The only problems I have with it are that:

* Terraform is complex in itself and pulls in a lot of code that I have to trust.
* The state file which sometimes gets corrupted (making Terraform not very reliable).

Additionally, I initially thought that gmailctl would be easy to implement and not require any knowledge of complex machinery (like Terraform or similar tools), which turned out to be only partially true :)
gmailctl grew organically and the first version was just a few lines of code generating an XML. If I knew all the features I ended up needing in advance maybe I would have chosen a different path.

I would definitely recommend starting with Terraform now. If you find it not working to your liking you can always ditch it and re-implement the parts that you need. If it does work out you can save some time.

**Comment by magodo** [comment]
Thank you for your reply :)
