### ISSUE TITLE
QUESTION: Limit on number of emails in each filter

### ISSUE THREAD

**Issue by iwconfig** [mbrt/gmailctl#148]
Hi there,

I'm asking in advance before I invest my time in this seemingly spectacular tool.

I have to filter out _a lot_ of spam emails and delete them. Since Gmail has a limit of 1500 chars per filter, I can only filter out a certain number of emails. I can solve this by creating multiple filters doing the same thing but each with a different set of spam emails.

Would I have to do the same with gmailctl? If not, I would assume gmailctl creates multiple filters for me automatically, correct? Can I store say a hundred thousand emails in a list and gmailctl takes care of it?

**Comment by mbrt** [comment]
gmailctl automatically splits filters whenever possible, to avoid the size limit. If you declare your filter like so:

```jsonnet
local spam = {
  or: [
    { from: 'foo@bar.com' },
    { from: 'baz@bar.com' },
    { list: 'wow@list.com' },
    // ...
  ],
};

{
  rules: [
    {
      filter: spam,
      actions: { delete: true },
    },
  ],
}
```

You should get a bunch of filters, and not only one. I'm not entirely sure about two things:

1. Is Gmail able to handle hundred of thousands of filters?
2. Is gmailctl smart enough to prioritize the `or` splitting ([here](https://github.com/mbrt/gmailctl/blob/c661a9d8d87bb65b8fc287cbd7f74e5ad164dcd5/pkg/filter/convert.go#L27)) even when the functions can be merged together ([here](https://github.com/mbrt/gmailctl/blob/c661a9d8d87bb65b8fc287cbd7f74e5ad164dcd5/pkg/parser/ast.go#L166-L167))?

If 2) doesn't work, it should be easy to fix, but there's nothing we can do about 1).

You can easily test your situation by creating a sample config and then, instead of spending time initializing the APIs, just use `gmailctl export` to take a loot at the generated XML.
