### ISSUE TITLE
Oauth Token expires weekly

### ISSUE THREAD

**Issue by matthewoden** [mbrt/gmailctl#171]
I don't know if this is an issue with my credentials, or the gmailctl token handler, but I've found that my credentials.json has to be updated roughly every week.

```
Error: getting filters from Gmail: Get "https://gmail.googleapis.com/gmail/v1/users/me/labels?alt=json&prettyPrint=false": oauth2: cannot fetch token: 400 Bad Request
Response: {
  "error": "invalid_grant",
  "error_description": "Token has been expired or revoked."
}
```

I noticed the setup instructions are out of date (there's nothing about setting up a test user as part of your oauth client),  I'm not sure if this is a bug on the setup instructions missing a step, if google has changed their token lifetimes for unverified test apps, or if this is really just a _me_ issue.

**Comment by mbrt** [comment]
Oh I actually got the same exact problem today. There seems to be some difference with how Gmail issues the tokens nowadays and they just expire :/

Good news is that I now have a way to reproduce the problem. Hopefully I'll find a way to fix it. Issuing API calls towards your own account: how hard can it be?

**Comment by matthewoden** [comment]
So, I found part of the issue while debugging another project of mine that uses google apps-scripts. If it's an external app, the scopes used require verification.

[If you're just developing/testing, you're stuck in this mess](https://developers.google.com/identity/protocols/oauth2#expiration)
> a Google Cloud Platform project with an OAuth consent screen configured for an external user type and a publishing status of "Testing" is issued a refresh token expiring in 7 days.

In order to publish an app, you need to provide a bunch of stuff, a privacy policy, a youtube video describing how you plan to handle privacy, etc. Which is a whole lot of work for something you just want to use for yourself. Bleh.

I haven't looked at service accounts yet, but I might [run through this](https://ebstalimited.zendesk.com/hc/en-us/articles/360017031473-How-to-a-create-a-Gmail-service-account) to see if that can get me some useful, long-lived creds.

**Comment by mbrt** [comment]
I think I found the way to get around the problem. See https://support.google.com/cloud/answer/9110914?hl=en#zippy=%2Cwhat-app-types-are-not-applicable-for-verification.

* If you are a member of an organization, you can mark the application as 'Internal' in the 'OAuth consent screen'.
* Make sure 'Publishing status' is set to 'In production', *do not use the Testing mode*. If the app is in testing mode, you need to publish it *without submitting for verification*.

All in all the instructions provided by gmailctl seem correct. I probably need to add a disclaimer warning against the testing mode, which has the 7 days expiration limitation.

Let me know if this works for you.

P.S. The service account only works within an organization, because they require 'Domain level delegation', which needs to be enabled by the admin of your organization. See for example the instructions for RClone and Google Drive, which go through the very same verification process: https://rclone.org/drive/.

**Comment by matthewoden** [comment]
Ah, so I can publish and just not submit the materials? Perfect! I think I'll be all set. If this blows up on me again, I'll report back. I'll go ahead and close this for now.

**Comment by matthewoden** [comment]
It's been 8 days since I created my token, and I ran into the expired token issue again. BUT, this was the project that was set up incorrectly, so my whole setup on that project might just be hosed.

To test this, I've created a brand new project, and run through the recommended setup. I guess I'll check back in, after another week.

**Comment by workflow** [comment]
Thanks this is helpful! Testing it with a published but unverified app now as well, will also report if the token expires again after 7 days.

Just one note that took me a while to figure out:

To reset the old token, it's not enough to delete `credentials.json` and re-run `gmailctl init` on the new `credentials.json`. Instead there seems to be some caching involved somewhere, and I had to run
```
gmailctl init --reset
```
...in order for it to pick up the new token.

Thanks for this project @mbrt :)
