### ISSUE TITLE
Is there a particular reason why isEscaped / isRaw cannot be used for cc / bcc?

### ISSUE THREAD

**Issue by dlenkes** [mbrt/gmailctl#290]
Hi,

I am setting up some filters where I want to catch +XYZ for cc or bcc. 
In order to get the correct result in the gmail UI, I set up a filter, like: cc:"\\+XYZ" 

However when I try to do this in my config, I get the following error:

```
$ gmailctl diff /home/dlenkes/.gmailctl/config.jsonnet
Error: cannot parse config file: rule #113: parsing criteria: 'isRaw' can be used only with fields from, to, subject

Note: 
  - Rule: {
      "filter": {
        "or": [
          {
            "to": "\"/(.*)\\+activity(.*)\\@gmail.com$/\"",
            "isEscaped": true
          },
          {
            "cc": "\"/(.*)\\+activity(.*)\\@gmail.com$/\"",
            "isEscaped": true
          },
          {
            "bcc": "\"/(.*)\\+activity(.*)\\@gmail.com$/\"",
            "isEscaped": true
          },
          {
            "from": "\"/(.*)\\+activity(.*)\\@gmail.com$/\"",
            "isEscaped": true
          }
        ]
      },
      "actions": {
        "archive": true,
        "markSpam": false,
        "markImportant": false,
        "labels": [
          "automation"
        ]
      }
    }

```
I see the validation here:
https://github.com/mbrt/gmailctl/blob/adfcb367ed50a851f32dc085f8983f5ac5469f46/internal/engine/parser/parser.go#L108

Why is it not allowed for cc / bcc?
It looks like the UI supports it so I am wondering if it is possible to do enable it for them.

Thanks,
Daniel

**Comment by mbrt** [comment]
Hey Daniel. There's no need to escape `+`, as Gmail filter's syntax doesn't support regular expressions. You can try using the Gmail search bar but I'm pretty sure your expressions shouldn't work.

If these are aliases of your email, I recommend just making them explicit:

```
to: "my-mail+activity@gmail.com"
```

To elaborate on why `isRaw` is available only in those fields: it's because these are the only "real" fields supported by Gmail APIs. When filters are imported through `gmailctl download` it's not always possible to unescape and decompose the contents into native gmailctl expressions, so `isRaw` was introduced. It's not meant to be used directly basically.

If you need to use operators other than the ones supported, or you want to avoid any escaping, you can always use the `query` field:

```
query: "from: \"foo\" has:attachment"
```

**Comment by dlenkes** [comment]
Hi Michele,

Thanks for the reply.

I am still learning the mysterious ways of gmail filters, and read somewhere that you can force gmail this way to actually use regex. After experimenting with it, sadly, it looks like you are right, it does not exactly work as I hoped for.

Thanks for the insights!

Best,
Daniel

**Comment by mbrt** [comment]
It is indeed quite mysterious. Cheers
