### ISSUE TITLE
intersection by default

### ISSUE THREAD

**Issue by FranklinYu** [mbrt/gmailctl#74]
This is a feature request.

Current:

```jsonnet
{
  filter: {
    and: [
      { from: 'ticketsroleaccount <buganizer-system+ticketsroleaccount@google.com>' },
      {
        not: { to: me }
      },
    ],
  },
}
```

I would like:

```jsonnet
{
  filter: {
    from: 'ticketsroleaccount <buganizer-system+ticketsroleaccount@google.com>',
    not: { to: me },
  },
}
```

This behavior is same as search, and is backward compatible (test whether there are more than one key).

**Comment by mbrt** [comment]
A previous version (I believe 1alpha1) was actually doing that, but it's been changed the way it is now because:

* It's not clear why `and` should be any different than `or`;
* The syntax wouldn't allow multiple entries with the same operator at the same time (e.g. multiple `from`).

Operators like `from` could take arrays as operands, but it would be even more confusing.

**Comment by FranklinYu** [comment]
> It's not clear why `and` should be any different than `or`;

Because GMail team think so?

> The syntax wouldn't allow multiple entries with the same operator at the same time (e.g. multiple `from`).

One can always fall back to `and` operator for this case. Sorry I didn’t make it clear but I’m proposing a syntax addition (“sugar”) instead of a change. This also makes it backward compatible; ones who prefer to be explicit can continue doing that.

**Comment by mbrt** [comment]
> Because GMail team think so?

GMail uses a search box. This is instead a configuration language, so I think it's better to use conventions from the programming languages area, where `and` is not implicit.

> One can always fall back to and operator for this case. Sorry I didn’t make it clear but I’m proposing a syntax addition (“sugar”) instead of a change. This also makes it backward compatible; ones who prefer to be explicit can continue doing that.

Adding sugar can always be done with additional functions in your config directly. I'm always resistant in adding shortcuts in the language because I believe in [explicit is better than implicit](https://www.python.org/dev/peps/pep-0020/), plus having more than one way of doing the same thing decreases readability.

Everything I add has to be supported in the future and I'm especially careful about changing the config format. I don't think this change would bring enough value to justify the potential trouble in the future.

I hope this explains my reasoning.
